apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servatrice.fullname" . }}
  labels:
    {{- include "servatrice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "servatrice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "servatrice.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "servatrice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - servatrice
            - '--config'
            - '/tmp/servatrice.ini'
            - '--log-to-console'
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: socket
              containerPort: 4748
              protocol: TCP
            - name: http
              containerPort: 4747
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: volume-servatrice-ini
      volumes:
        - configMap:
            defaultMode: 420
            name: servatrice-servatrice.ini
          name: volume-servatrice-ini
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
