# This is a basic workflow to help you get started with Actions

name: publish-chart

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  helm-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: helm package
        run: helm package ./charts/servatrice --destination .deploy
      - uses: actions/upload-artifact@master
        with:
          name: charts
          path: .deploy
  chart-release:
    runs-on: ubuntu-latest
    name: chart release
    needs: [helm-package]
    container: 
      image: quay.io/helmpack/chart-release
      env:
        CR_OWNER: "FociSolutions"
        CR_GIT_REPO: "helm-charts"
        CR_PACKAGE_PATH: ".deploy"
        CR_TOKEN:  "${{ secrets.GITHUB_TOKEN }}"
        CR_GIT_BASE_URL: "https://api.github.com/"
        CR_GIT_UPLOAD_URL: "https://uploads.github.com/"        
    steps:
      - uses: actions/download-artifact@master
        name: download charts
        with:
          name: charts
          path: .deploy
      - name: generate index
        run: cr index -i ./index.yaml
      - uses: actions/upload-artifact@master
        name: upload index
        with:
          name: index
          path: ./index.yaml
  publish-index:
    runs-on: [ubuntu-latest]
    name: publish index
    needs: [chart-release]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: index
          path: ./index.yaml
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.0
        with:
          dir: cr-index
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
