# This is a basic workflow to help you get started with Actions

name: publish-chart

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://quay.io/helmpack/chart-releaser
    - name: Run a one-line script
      env:
        CR_OWNER: "FociSolutions"
        CR_GIT_REPO: "helm-charts"
        CR_PACKAGE_PATH: ".deploy"
        CR_TOKEN:  "${{ secrets.GITHUB_TOKEN }}"
        CR_GIT_BASE_URL: "https://api.github.com/"
        CR_GIT_UPLOAD_URL: "https://uploads.github.com/"  
      run: |
        Helm package charts/servatrice --destination .deploy
        cr upload
        cr index -i ./cr-index/index.yaml
    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.0
      with:
        dir: cr-index
        branch: gh-pages
        token: ${{ secrets.ACCESS_TOKEN }}
